{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "c75ad2a9",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-09-27 22:04:25.084160: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n"
     ]
    }
   ],
   "source": [
    "from keras_tuner import HyperModel\n",
    "import keras_tuner as kt\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "#!pip install keras_tuner\n",
    "#import keras_tuner\n",
    "\n",
    "import keras\n",
    "from keras import models, layers, metrics, Sequential\n",
    "from keras.layers import Dense, BatchNormalization, Dropout\n",
    "import tensorflow as tf\n",
    "from keras.regularizers import l1,l2,l1_l2\n",
    "from sklearn.metrics import mean_squared_error\n",
    "from tensorflow.keras.layers import Input, Dense, Multiply, Concatenate\n",
    "from tensorflow.keras.models import Model\n",
    "\n",
    "import tensorflow as tf\n",
    "import random\n",
    "\n",
    "import keras_tuner\n",
    "from keras_tuner import HyperModel\n",
    "import keras_tuner as kt\n",
    "\n",
    "from sklearn.preprocessing import MinMaxScaler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "0c6f6c5c",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Import Dataset\n",
    "firm_df = pd.read_pickle('firm_df49.pkl')\n",
    "firm_df.index = pd.to_datetime(firm_df.index).to_period('M')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "32ed8bbd",
   "metadata": {},
   "outputs": [],
   "source": [
    "char_core = ['acc','agr','beta','bm','cash','cashpr','cfp','chatoia','chcsho','chfeps','chinv',\n",
    "       'chmom','chpmia','chtx','currat','depr','dy','ear','ep','gma','grcapx','grltnoa',\n",
    "       'ill','indmom','invest','lev','lgr','maxret','mom12m','mom1m','mom36m','mve','nincr',\n",
    "       'orgcap','pchgm_pchsale','pchsale_pchinvt','pchsale_pchrect','pchsale_pchxsga',\n",
    "       'retvol','roaq','roavol','roeq','salecash','saleinv','sgr','sp','std_dolvol','std_turn','turn']\n",
    "\n",
    "info_list = ['fyear','year','jyear','permno','ticker','comnam','exchcd','exchname','siccd',\n",
    "       'indname','size_class','mve_m','rf','ret','ret_adj','ret_ex','ret_adj_ex',]\n",
    "\n",
    "macro_col = ['RPI', 'W875RX1', 'DPCERA3M086SBEA', 'CMRMTSPLx', 'RETAILx','INDPRO', 'IPFPNSS', 'IPFINAL', 'IPCONGD', 'IPDCONGD', 'IPNCONGD',\n",
    "       'IPBUSEQ', 'IPMAT', 'IPDMAT', 'IPNMAT', 'IPMANSICS', 'IPB51222S','IPFUELS', 'CUMFNS', 'HWI', 'HWIURATIO', 'CLF16OV', 'CE16OV',\n",
    "       'UNRATE', 'UEMPMEAN', 'UEMPLT5', 'UEMP5TO14', 'UEMP15OV','UEMP15T26', 'UEMP27OV', 'CLAIMSx', 'PAYEMS', 'USGOOD',\n",
    "       'CES1021000001', 'USCONS', 'MANEMP', 'DMANEMP', 'NDMANEMP','SRVPRD', 'USTPU', 'USWTRADE', 'USTRADE', 'USFIRE', 'USGOVT',\n",
    "       'CES0600000007', 'AWOTMAN', 'AWHMAN', 'HOUST', 'HOUSTNE','HOUSTMW', 'HOUSTS', 'HOUSTW', 'PERMIT', 'PERMITNE', 'PERMITMW',\n",
    "       'PERMITS', 'PERMITW', 'AMDMNOx', 'ANDENOx', 'AMDMUOx', 'BUSINVx','ISRATIOx', 'M1SL', 'M2SL', 'M2REAL', 'BOGMBASE', 'TOTRESNS',\n",
    "       'NONBORRES', 'BUSLOANS', 'REALLN', 'NONREVSL', 'CONSPI', 'S&P 500','S&P: indust', 'S&P div yield', 'S&P PE ratio', 'FEDFUNDS',\n",
    "       'CP3Mx', 'TB3MS', 'TB6MS', 'GS1', 'GS5', 'GS10', 'AAA', 'BAA','COMPAPFFx', 'TB3SMFFM', 'TB6SMFFM', 'T1YFFM', 'T5YFFM', 'T10YFFM',\n",
    "       'AAAFFM', 'BAAFFM', 'TWEXAFEGSMTHx', 'EXSZUSx', 'EXJPUSx','EXUSUKx', 'EXCAUSx', 'WPSFD49207', 'WPSFD49502', 'WPSID61',\n",
    "       'WPSID62', 'OILPRICEx', 'PPICMM', 'CPIAUCSL', 'CPIAPPSL','CPITRNSL', 'CPIMEDSL', 'CUSR0000SAC', 'CUSR0000SAD',\n",
    "       'CUSR0000SAS', 'CPIULFSL', 'CUSR0000SA0L2', 'CUSR0000SA0L5','PCEPI', 'DDURRG3M086SBEA', 'DNDGRG3M086SBEA', 'DSERRG3M086SBEA',\n",
    "       'CES0600000008', 'CES2000000008', 'CES3000000008', 'UMCSENTx','DTCOLNVHFNM', 'DTCTHFNM', 'INVEST', 'VIXCLSx', 'dp', 'ep_macro', 'b/m',\n",
    "       'ntis', 'tbl', 'tms', 'dfy', 'svar']\n",
    "\n",
    "macro_core =  ['dp', 'ep_macro', 'b/m','ntis', 'tbl', 'tms', 'dfy', 'svar']\n",
    "\n",
    "def datasplit(df, dataset):\n",
    "    df_train = df[df.index < pd.Period((str(1995)+\"-1\"),freq='M')]\n",
    "    df_val = df[(df.index >= pd.Period((str(1995)+\"-1\"),freq='M')) & (df.index < pd.Period((str(2000)+\"-1\"),freq='M'))]\n",
    "    df_test = df[df.index >= pd.Period((str(2000)+\"-1\"),freq='M')]\n",
    "    if dataset == \"firm\":\n",
    "        X_train = df_train[char_core]\n",
    "        X_val = df_val[char_core]\n",
    "        X_test = df_test[char_core]\n",
    "    elif dataset == 'macro':\n",
    "        X_train = df_train[macro_col]\n",
    "        X_val = df_val[macro_col]\n",
    "        X_test = df_test[macro_col]\n",
    "    elif dataset == \"firm_macro\":\n",
    "        X_train = df_train[char_core+macro_col]\n",
    "        X_val = df_val[char_core+macro_col]\n",
    "        X_test = df_test[char_core+macro_col]\n",
    "    elif dataset == \"firm_macro8\":\n",
    "        X_train = df_train[char_core+macro_core]\n",
    "        X_val = df_val[char_core+macro_core]\n",
    "        X_test = df_test[char_core+macro_core] \n",
    "    y_train = df_train['predicted_return']\n",
    "    y_val = df_val['predicted_return']\n",
    "    y_test = df_test['predicted_return']\n",
    "    return (X_train, y_train, X_val, y_val, X_test, y_test, )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "14a58230",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(88347, 49) (88347,) (31851, 49) (31851,) (90007, 49) (90007,)\n"
     ]
    }
   ],
   "source": [
    "X_train, y_train, X_val, y_val, X_test, y_test = datasplit(firm_df, dataset = \"firm\")\n",
    "print(X_train.shape, y_train.shape, X_val.shape, y_val.shape, X_test.shape, y_test.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "d2879da1",
   "metadata": {},
   "outputs": [],
   "source": [
    "def my_metric_fn(y_true, y_pred):\n",
    "    num = tf.reduce_mean(tf.square(y_true - y_pred))\n",
    "    den = tf.reduce_mean(tf.square(y_true))\n",
    "    return 1 - num / den\n",
    "\n",
    "class MyHyperModel(keras_tuner.HyperModel):\n",
    "    def build(self, hp, n_inputs=49,):\n",
    "        l1_reg = hp.Choice(\"l1_ratio\", [0.,])\n",
    "        l2_reg = hp.Choice(\"l2_ratio\", [0.001,])\n",
    "        dropout = hp.Choice(\"dropout\",[0.1, 0.])\n",
    "        lr = hp.Choice(\"learning_rate\", [0.001,0.0001])\n",
    "        \n",
    "        # Define the hidden layers \n",
    "        input_layer = Input(shape=(49,))\n",
    "        # Define hidden layers\n",
    "        hidden_layer1 = Dense(64, activation ='relu', kernel_regularizer=l1_l2(l1=l1_reg,l2=l2_reg))(input_layer)\n",
    "        dropout1 = Dropout(dropout)(hidden_layer1)\n",
    "        hidden_layer2 = Dense(32, activation ='relu', kernel_regularizer=l1_l2(l1=l1_reg,l2=l2_reg))(hidden_layer1)\n",
    "        dropout2 = Dropout(dropout)(hidden_layer2)        \n",
    "        hidden_layer3 = Dense(16, activation ='relu', kernel_regularizer=l1_l2(l1=l1_reg,l2=l2_reg))(hidden_layer2)\n",
    "        dropout3 = Dropout(dropout)(hidden_layer3)\n",
    "        hidden_layer4 = Dense(8, activation ='relu', kernel_regularizer=l1_l2(l1=l1_reg,l2=l2_reg))(hidden_layer2)\n",
    "        dropout4 = Dropout(dropout)(hidden_layer4)\n",
    "  \n",
    "        # Concatenate the last hidden layer with the input layer \n",
    "        concatenated_layer = Concatenate()([hidden_layer4, input_layer])\n",
    "        # Define output layer \n",
    "        output_layer = Dense(1,)(concatenated_layer)\n",
    "        # Create the model \n",
    "        model = Model(input_layer, output_layer)\n",
    "        opt = tf.keras.optimizers.Adam(learning_rate=lr)\n",
    "        model.compile(loss='mean_squared_error', optimizer=opt,metrics=[my_metric_fn])\n",
    "        return model\n",
    "    \n",
    "    def fit(self, hp, model, *args, **kwargs):\n",
    "        return model.fit(\n",
    "            *args,\n",
    "            batch_size=hp.Choice(\"batch_size\", [128,256]),\n",
    "            **kwargs,\n",
    "        )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "c5fbc9e7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Trial 8 Complete [00h 00m 24s]\n",
      "val_loss: 0.0146321477368474\n",
      "\n",
      "Best val_loss So Far: 0.014578191563487053\n",
      "Total elapsed time: 00h 08m 55s\n",
      "INFO:tensorflow:Oracle triggered exit\n"
     ]
    }
   ],
   "source": [
    "max_trials = 200\n",
    "train_epochs = 200\n",
    "\n",
    "tuner = keras_tuner.RandomSearch(MyHyperModel(),objective='val_loss',max_trials=max_trials,overwrite=True,)\n",
    "tuner.search(X_train, y_train, epochs=train_epochs, validation_data=(X_val, y_val), \n",
    "             callbacks=[keras.callbacks.EarlyStopping(monitor='val_loss', patience=3)])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "2ae69ee6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'l1_ratio': 0.0, 'l2_ratio': 0.001, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 128}\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 9.5559e-04\n",
      "Epoch 2/20\n",
      "3757/3757 [==============================] - 7s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0017\n",
      "Epoch 3/20\n",
      "3757/3757 [==============================] - 7s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0015\n",
      "Epoch 4/20\n",
      "3757/3757 [==============================] - 7s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0017\n",
      "Epoch 5/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0019\n",
      "Epoch 6/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0020\n",
      "Epoch 7/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0023\n",
      "Epoch 8/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0020\n",
      "Epoch 9/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0025\n",
      "Epoch 10/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0022\n",
      "Epoch 11/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0021\n",
      "Epoch 12/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0013\n",
      "Epoch 13/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0018\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0157 - my_metric_fn: 0.0034\n",
      "[0.01573152467608452, 0.003367922268807888]\n",
      "2813/2813 [==============================] - 4s 1ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/20\n",
      "3757/3757 [==============================] - 9s 2ms/step - loss: 0.0128 - my_metric_fn: 9.3861e-04\n",
      "Epoch 2/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0017\n",
      "Epoch 3/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0016\n",
      "Epoch 4/20\n",
      "3757/3757 [==============================] - 9s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0015\n",
      "Epoch 5/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0022\n",
      "Epoch 6/20\n",
      "3757/3757 [==============================] - 9s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0019\n",
      "Epoch 7/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0021\n",
      "Epoch 8/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0019\n",
      "Epoch 9/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0019\n",
      "Epoch 10/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0022\n",
      "Epoch 11/20\n",
      "3757/3757 [==============================] - 9s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0022\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0157 - my_metric_fn: 0.0016\n",
      "[0.015665102750062943, 0.0016084089875221252]\n",
      "2813/2813 [==============================] - 5s 2ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/20\n",
      "3757/3757 [==============================] - 10s 2ms/step - loss: 0.0128 - my_metric_fn: 4.2894e-04\n",
      "Epoch 2/20\n",
      "3757/3757 [==============================] - 7s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0014\n",
      "Epoch 3/20\n",
      "3757/3757 [==============================] - 7s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0019\n",
      "Epoch 4/20\n",
      "3757/3757 [==============================] - 7s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0018\n",
      "Epoch 5/20\n",
      "3757/3757 [==============================] - 7s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0020\n",
      "Epoch 6/20\n",
      "3757/3757 [==============================] - 7s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0021\n",
      "2813/2813 [==============================] - 4s 1ms/step - loss: 0.0157 - my_metric_fn: 0.0021\n",
      "[0.01565137319266796, 0.0020898268558084965]\n",
      "2813/2813 [==============================] - 6s 2ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 8.7726e-04\n",
      "Epoch 2/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0018\n",
      "Epoch 3/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0019\n",
      "Epoch 4/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0016\n",
      "Epoch 5/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0016\n",
      "Epoch 6/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0019\n",
      "Epoch 7/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0022\n",
      "Epoch 8/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0019\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0157 - my_metric_fn: 0.0043\n",
      "[0.015672944486141205, 0.0042677754536271095]\n",
      "2813/2813 [==============================] - 4s 1ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 9.5202e-04\n",
      "Epoch 2/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0013\n",
      "Epoch 3/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0017\n",
      "Epoch 4/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0015\n",
      "Epoch 5/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0020\n",
      "Epoch 6/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0018\n",
      "Epoch 7/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0019\n",
      "Epoch 8/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0020\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0157 - my_metric_fn: 0.0018\n",
      "[0.015727892518043518, 0.0017730206018313766]\n",
      "2813/2813 [==============================] - 4s 2ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0010\n",
      "Epoch 2/20\n",
      "3757/3757 [==============================] - 7s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0011\n",
      "Epoch 3/20\n",
      "3757/3757 [==============================] - 7s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0015\n",
      "Epoch 4/20\n",
      "3757/3757 [==============================] - 7s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0016\n",
      "Epoch 5/20\n",
      "3757/3757 [==============================] - 7s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0018\n",
      "Epoch 6/20\n",
      "3757/3757 [==============================] - 7s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0017\n",
      "Epoch 7/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0017\n",
      "Epoch 8/20\n",
      "3757/3757 [==============================] - 14s 4ms/step - loss: 0.0128 - my_metric_fn: 0.0020\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0157 - my_metric_fn: 0.0056\n",
      "[0.01568034663796425, 0.005599538795650005]\n",
      "2813/2813 [==============================] - 4s 1ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/20\n",
      "3757/3757 [==============================] - 10s 2ms/step - loss: 0.0128 - my_metric_fn: 7.2477e-04\n",
      "Epoch 2/20\n",
      "3757/3757 [==============================] - 11s 3ms/step - loss: 0.0128 - my_metric_fn: 0.0018\n",
      "Epoch 3/20\n",
      "3757/3757 [==============================] - 10s 3ms/step - loss: 0.0128 - my_metric_fn: 0.0017\n",
      "Epoch 4/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0019\n",
      "Epoch 5/20\n",
      "3757/3757 [==============================] - 15s 4ms/step - loss: 0.0128 - my_metric_fn: 0.0020\n",
      "Epoch 6/20\n",
      "3757/3757 [==============================] - 19s 5ms/step - loss: 0.0128 - my_metric_fn: 0.0021\n",
      "Epoch 7/20\n",
      "3757/3757 [==============================] - 11s 3ms/step - loss: 0.0128 - my_metric_fn: 0.0021\n",
      "Epoch 8/20\n",
      "3757/3757 [==============================] - 10s 3ms/step - loss: 0.0128 - my_metric_fn: 0.0019\n",
      "Epoch 9/20\n",
      "3757/3757 [==============================] - 9s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0021\n",
      "Epoch 10/20\n",
      "3757/3757 [==============================] - 10s 3ms/step - loss: 0.0128 - my_metric_fn: 0.0022\n",
      "2813/2813 [==============================] - 6s 2ms/step - loss: 0.0157 - my_metric_fn: 0.0048\n",
      "[0.015664804726839066, 0.004834773018956184]\n",
      "2813/2813 [==============================] - 6s 2ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/20\n",
      "3757/3757 [==============================] - 9s 2ms/step - loss: 0.0128 - my_metric_fn: 8.7632e-04\n",
      "Epoch 2/20\n",
      "3757/3757 [==============================] - 9s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0017\n",
      "Epoch 3/20\n",
      "3757/3757 [==============================] - 9s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0016\n",
      "Epoch 4/20\n",
      "3757/3757 [==============================] - 9s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0020\n",
      "Epoch 5/20\n",
      "3757/3757 [==============================] - 9s 3ms/step - loss: 0.0128 - my_metric_fn: 0.0016\n",
      "Epoch 6/20\n",
      "3757/3757 [==============================] - 9s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0019\n",
      "Epoch 7/20\n",
      "3757/3757 [==============================] - 9s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0020\n",
      "Epoch 8/20\n",
      "3757/3757 [==============================] - 9s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0018\n",
      "Epoch 9/20\n",
      "3757/3757 [==============================] - 9s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0026\n",
      "Epoch 10/20\n",
      "3757/3757 [==============================] - 9s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0016\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0157 - my_metric_fn: 0.0048\n",
      "[0.015674157068133354, 0.004817526321858168]\n",
      "2813/2813 [==============================] - 5s 2ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 8.8696e-04\n",
      "Epoch 2/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0014\n",
      "Epoch 3/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0015\n",
      "Epoch 4/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0015\n",
      "Epoch 5/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0020\n",
      "Epoch 6/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0018\n",
      "Epoch 7/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0017\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0157 - my_metric_fn: 0.0025\n",
      "[0.01572246477007866, 0.0024911570362746716]\n",
      "2813/2813 [==============================] - 4s 1ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/20\n",
      "3757/3757 [==============================] - 9s 2ms/step - loss: 0.0128 - my_metric_fn: 8.5635e-04\n",
      "Epoch 2/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0019\n",
      "Epoch 3/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0014\n",
      "Epoch 4/20\n",
      "3757/3757 [==============================] - 9s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0016\n",
      "Epoch 5/20\n",
      "3757/3757 [==============================] - 8s 2ms/step - loss: 0.0128 - my_metric_fn: 0.0023\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0157 - my_metric_fn: 0.0020\n",
      "[0.01572149246931076, 0.002038634615018964]\n",
      "2813/2813 [==============================] - 4s 2ms/step\n",
      "\n",
      "0.005179291444543543\n"
     ]
    }
   ],
   "source": [
    "# 10 Trials for Prediction\n",
    "x_all = np.concatenate((X_train, X_val))\n",
    "y_all = np.concatenate((y_train, y_val))\n",
    "best_hps = tuner.get_best_hyperparameters(5)\n",
    "print(best_hps[0].values)\n",
    "seed_list = [458, 165, 530, 564, 590, 560, 829, 170, 376, 176]\n",
    "yhat_df = pd.DataFrame()\n",
    "\n",
    "for random_seed in seed_list:\n",
    "    random.seed(random_seed)\n",
    "    np.random.seed(random_seed)\n",
    "    tf.random.set_seed(random_seed)\n",
    "\n",
    "    best_model = tuner.get_best_models(3)[0]\n",
    "    best_model.fit(x=x_all, y=y_all, epochs=20,\n",
    "              callbacks=[keras.callbacks.EarlyStopping(monitor='loss',mode='min', patience=2)])\n",
    "    print(best_model.evaluate(X_test,y_test))\n",
    "    y_hat = best_model.predict(X_test).reshape(-1)\n",
    "    yhat_df[random_seed] = y_hat\n",
    "    print()\n",
    "\n",
    "# Print out Predictive R^2\n",
    "y_predict = yhat_df.mean(axis=1).values.reshape(-1)\n",
    "y_real = y_test\n",
    "\n",
    "a = np.mean(np.square(y_predict -  y_real))\n",
    "b = np.mean(np.square(y_real))\n",
    "print(1-a/b)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "14471431",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0.005455629526289751\n"
     ]
    }
   ],
   "source": [
    "\n",
    "a = np.mean(np.square(y_predict -  y_real))\n",
    "b = np.mean(np.square(y_real))\n",
    "print(1-a/b)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "772750c7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
